trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

    - task: SonarCloudPrepare@1
      displayName: 'Prepare Sonar-Cloud analysis'
      inputs:
        SonarCloud: 'qlector-azurepipelines'
        organization: 'madsciencist-github'
        scannerMode: 'MSBuild'
        projectKey: 'MadSciencist_QLector'
        projectName: 'qlector'
        extraProperties: 'sonar.cs.opencover.reportsPaths=$(build.sourcesdirectory)/target/reports/coverage/coverage.opencover.xml'

    - task: UseDotNet@2 
      displayName: "Use .NET Core 3.1 (SDK)"
      inputs:
        version: '3.1.x'
        packageType: sdk

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'Build with config: $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: "Run Tests"
      inputs:
        command: test
        projects: 'tests/**/*.csproj'
        arguments: '--configuration $(BuildConfiguration) --no-build /p:CollectCoverage=true /p:IncludeTestAssembly=true /p:CoverletOutputFormat=opencover%2ccobertura /p:CoverletOutput=../../target/reports/coverage/'
    
    - task: UseDotNet@2 
      displayName: "Use .NET Core 2.1 (for Sonar-Cloud)"
      inputs:
        version: '2.0.x'
        packageType: runtime
    - task: SonarCloudAnalyze@1
      displayName: 'Sonar-Cloud: analysis'

    - task: SonarCloudPublish@1
      displayName: 'Sonar-Cloud: publish results'
      inputs:
        pollingTimeoutSec: '300'

    - task: UseDotNet@2 
      displayName: "Use .NET Core 3.1"
      inputs:
        version: '3.1.x'
        packageType: sdk
        
    - task: Palmmedia.reportgenerator.reportgenerator-build-release-task.reportgenerator@4
      displayName: Generate coverage report
      inputs:
        reports: 'target/reports/coverage/coverage.opencover.xml'
        targetdir: 'target/reports/coverage'
        reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'
        assemblyfilters: '-xunit*'
        verbosity: 'Verbose'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish coverage results'
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(build.sourcesdirectory)/target/reports/coverage/coverage.cobertura.xml'
        reportDirectory: '$(build.sourcesdirectory)/target/reports/coverage'

    - task: DotNetCoreCLI@2
      displayName: "Create build artifacts"
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: "Upload Artifacts"
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'app-linux-x64' 