###
POST http://localhost:5005/api/user/login HTTP/1.1
content-type: application/json
accept: application/json

{
    "login": "matty5422444",
    "password": "passw1"
}

###

POST http://localhost:5005/api/user/register HTTP/1.1
content-type: application/json
accept: application/json

{
    "userName": "matty54224442",
    "password": "passw1",
    "email": "matty@matty42542424.com"
}